import "../styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { getSession } from "~/server/better-auth/server";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "WatchLists",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getSession();
  return (
    <html lang="en" className="dark">
      <body className={`${geist.className} bg-background text-foreground`}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        {!session && (
          <main className="flex flex-col items-center justify-center text-white">
            {children}
          </main>
        )}
      </body>
    </html>
  );
}
