import "../styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { getSession } from "~/server/better-auth/server";

import { Toast } from "@heroui/react";
import { TRPCReactProvider } from "~/trpc/react";
import SidebarWrapper from "./_components/sidebar/sidebar-wrapper";
import { UserPreferencesProvider } from "./_components/user-preferences";

export const metadata: Metadata = {
  title: "WatchLists",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getSession();
  return (
    <html lang="en" className="dark">
      <body className={`${geist.className} bg-background text-foreground`}>
        <TRPCReactProvider>
          {session ? (
            <UserPreferencesProvider>
            <div className="flex h-screen overflow-hidden">
              <SidebarWrapper />
              <main className="flex-1 overflow-y-auto">{children}</main>
            </div>
            </UserPreferencesProvider>
          ) : (
            <main className="flex min-h-screen flex-col items-center justify-center">
              {children}
            </main>
          )}
          <Toast.Provider />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
